steps:

- label: Install Python
  command: |
    apt-get update
    apt-get install -y python3 python3-pip
    python3 -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install pytest

- wait

- label: ':pytest: PyTest I'
  command: PYTHONPATH=test python3 -m pytest test --continue-on-collection-errors --junit-xml pytest.xml
  artifact_paths: "pytest*.xml"
  timeout_in_minutes: 2

- label: ':pytest: PyTest II'
  command: PYTHONPATH=test python3 -m pytest test --continue-on-collection-errors --junit-xml pytest.xml
  artifact_paths: "pytest*.xml"
  timeout_in_minutes: 1
