name: "Checks"
on: push

jobs:
  checks:
    name: "Checks"

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Update 0
      if: always()
      run: |
        sleep 2
        curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/EnricoMi/python/check-runs/6119658603 -d @checks/update-check-run-validation-failed.0.json

    - name: Update 1
      if: always()
      run: |
        sleep 2
        curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/EnricoMi/python/check-runs/6119658603 -d @checks/update-check-run-validation-failed.1.json

    - name: Update 2
      if: always()
      run: |
        sleep 2
        curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/EnricoMi/python/check-runs/6119658603 -d @checks/update-check-run-validation-failed.2.json

    - name: Update 3
      if: always()
      run: |
        sleep 2
        curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/EnricoMi/python/check-runs/6119658603 -d @checks/update-check-run-validation-failed.3.json

    - name: Update 4
      if: always()
      run: |
        sleep 2
        curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/EnricoMi/python/check-runs/6119658603 -d @checks/update-check-run-validation-failed.4.json

    - name: Update 5
      if: always()
      run: |
        sleep 2
        curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/EnricoMi/python/check-runs/6119658603 -d @checks/update-check-run-validation-failed.5.json

    - name: Update 6
      if: always()
      run: |
        sleep 2
        curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/EnricoMi/python/check-runs/6119658603 -d @checks/update-check-run-validation-failed.6.json

    - name: Update 7
      if: always()
      run: |
        sleep 2
        curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/EnricoMi/python/check-runs/6119658603 -d @checks/update-check-run-validation-failed.7.json

    - name: Update 8
      if: always()
      run: |
        sleep 2
        curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/EnricoMi/python/check-runs/6119658603 -d @checks/update-check-run-validation-failed.8.json

    - name: Update 9
      if: always()
      run: |
        sleep 2
        curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/EnricoMi/python/check-runs/6119658603 -d @checks/update-check-run-validation-failed.9.json

    - name: Update 10
      if: always()
      run: |
        sleep 2
        curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/EnricoMi/python/check-runs/6119658603 -d @checks/update-check-run-validation-failed.10.json

    - name: Update 11
      if: always()
      run: |
        sleep 2
        curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/EnricoMi/python/check-runs/6119658603 -d @checks/update-check-run-validation-failed.11.json

    - name: Update 12
      if: always()
      run: |
        sleep 2
        curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/EnricoMi/python/check-runs/6119658603 -d @checks/update-check-run-validation-failed.12.json

    - name: Update 13
      if: always()
      run: |
        sleep 2
        curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/EnricoMi/python/check-runs/6119658603 -d @checks/update-check-run-validation-failed.13.json

    - name: Update 14
      if: always()
      run: |
        sleep 2
        curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/EnricoMi/python/check-runs/6119658603 -d @checks/update-check-run-validation-failed.14.json

    - name: Update 15
      if: always()
      run: |
        sleep 2
        curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/EnricoMi/python/check-runs/6119658603 -d @checks/update-check-run-validation-failed.15.json

    - name: Update 16
      if: always()
      run: |
        sleep 2
        curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/EnricoMi/python/check-runs/6119658603 -d @checks/update-check-run-validation-failed.16.json

    - name: Update 17
      if: always()
      run: |
        sleep 2
        curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/EnricoMi/python/check-runs/6119658603 -d @checks/update-check-run-validation-failed.17.json

    - name: Update 18
      if: always()
      run: |
        sleep 2
        curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/EnricoMi/python/check-runs/6119658603 -d @checks/update-check-run-validation-failed.18.json

    - name: Update 19
      if: always()
      run: |
        sleep 2
        curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/EnricoMi/python/check-runs/6119658603 -d @checks/update-check-run-validation-failed.19.json

    - name: Update 20
      if: always()
      run: |
        sleep 2
        curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/EnricoMi/python/check-runs/6119658603 -d @checks/update-check-run-validation-failed.20.json

    - name: Update 21
      if: always()
      run: |
        sleep 2
        curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/EnricoMi/python/check-runs/6119658603 -d @checks/update-check-run-validation-failed.21.json

    - name: Update 22
      if: always()
      run: |
        sleep 2
        curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/EnricoMi/python/check-runs/6119658603 -d @checks/update-check-run-validation-failed.22.json

    - name: Update 23
      if: always()
      run: |
        sleep 2
        curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/EnricoMi/python/check-runs/6119658603 -d @checks/update-check-run-validation-failed.23.json

    - name: Update 24
      if: always()
      run: |
        sleep 2
        curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/EnricoMi/python/check-runs/6119658603 -d @checks/update-check-run-validation-failed.24.json

    - name: Update 25
      if: always()
      run: |
        sleep 2
        curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/EnricoMi/python/check-runs/6119658603 -d @checks/update-check-run-validation-failed.25.json

    - name: Update 26
      if: always()
      run: |
        sleep 2
        curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/EnricoMi/python/check-runs/6119658603 -d @checks/update-check-run-validation-failed.26.json

