name: "Checks"
on: push

jobs:
  checks:
    name: "Checks"

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Update
      run: |
        for file in checks/check*.json
        do
          sleep 2
          echo "##[group]$file"
          cat "$file"
          curl -X PATCH -H "Accept: application/vnd.github.v3+json" -H "Content-Type: application/json; charset=utf-8" -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/EnricoMi/python/check-runs/6119658603 -d "@$file" || true
          echo "##[endgroup]"
        done

