name: "CI"
on: [push, pull_request, workflow_dispatch]
permissions: {}

jobs:
  publish_test_results:
    name: "Publish Unit Tests"
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    if: always()

    steps:
      - name: Download and Extract Artifacts
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          mkdir -p artifacts && cd artifacts

          artifacts_url=https://api.github.com/repos/ben-manes/caffeine/actions/runs/2614411522/artifacts

          gh api "$artifacts_url" -q '.artifacts[] | [.name, .archive_download_url] | @tsv' | while read artifact
          do
            IFS=$'\t' read name url <<< "$artifact"
            gh api $url > "$name.zip"
            unzip -d "$name" "$name.zip"
          done
      - name: Decompress
        run: |
          find . -type f -name '*.tar.gz' -exec sh -c 'tar -zxf {} --one-top-level' \;
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          ignore_runs: true
          files: '**/TEST-*.xml'
