name: "CI"
on: [push, pull_request_target]

jobs:
  build_and_test:
    name: "Build and Test"

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Test with pytest
      run: |
        mkdir -p test-results
        python -m pytest test --junit-xml test-results/pytest.xml

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Unit Test Results ${{ matrix.python-version }}
        path: "test-results/**/*.xml"

  publish_test_results:
    name: "Publish Unit Tests"
    needs: build_and_test
    runs-on: ubuntu-latest
    if: always()

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        path: artifacts

    - name: Debug Action
      uses: hmarr/debug-action@v1.0.0

    - name: Publish Unit Test Results (I)
      uses: EnricoMi/publish-unit-test-result-action@master
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: "artifacts/**/*.xml"
        check_name: Publish Unit Test Results (I)
        hide_comments: off
        log_level: DEBUG

    - name: Publish Unit Test Results (II)
      uses: EnricoMi/publish-unit-test-result-action@master
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: "test/junit.xml"
        check_name: Publish Unit Test Results (II)
        hide_comments: off
        log_level: DEBUG

    - name: Publish Unit Test Results (III)
      uses: EnricoMi/publish-unit-test-result-action@master
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: "test/empty.xml"
        check_name: Publish Unit Test Results (III)
        hide_comments: off
        log_level: DEBUG

    - name: Publish Unit Test Results (IV)
      uses: EnricoMi/publish-unit-test-result-action@master
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: "test/non-existing.xml"
        check_name: Publish Unit Test Results (IV)
        hide_comments: off
        log_level: DEBUG
