name: "CI"
on: [push]

jobs:
  debug:
    name: "Debug-${{ matrix.x }}-${{ matrix.y }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        x: [1,2,3,4]
        y: [1,2,3,4]

    steps:
      - name: Cleanup Disk Space
        # deleting these paths frees 38 GB disk space:
        #   sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
        # but this sometimes takes 3-4 minutes
        # so we delete only some sub-paths which are known to be quick (10s) and 24 GB
        run: |
          echo ::group::Disk space before cleanup
          df -h
          echo ::endgroup::

          for dir in /usr/share/dotnet/sdk/\*/nuGetPackagesArchive.lzma \
                     /usr/share/dotnet/shared \
                     /usr/local/lib/android/sdk/ndk \
                     /usr/local/lib/android/sdk/build-tools \
                     /opt/ghc
          do
            echo ::group::Deleting "$dir"
            sudo du -hsc $dir | tail -n1 || true
            sudo rm -rf $dir
            echo ::endgroup::
          done

          echo ::group::Disk space after cleanup
          df -h
          echo ::endgroup::

