name: "CI"
on: [push, pull_request]

jobs:
  event_file:
    name: "Event File"
    runs-on: ubuntu-latest
    steps:
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Event File
        path: ${{ github.event_path }}

  test_hashfiles_files:
    name: "Test hashFiles"
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ hashFiles('**/*.txt') }}"
    - run: echo "content" > file1.txt
    - run: echo "${{ hashFiles('**/*.txt') }}"
    - run: echo "binary" > file2.txt
    - run: echo "${{ hashFiles('**/*.txt') }}"
    - run: chmod ugo-rwx file2.txt
    - run: echo "${{ hashFiles('**/*.txt') }}"

  test_hashfiles_dir:
    name: "Test hashFiles"
    runs-on: ubuntu-latest
    steps:
    - run: mkdir dir1 dir2
    - run: echo "${{ hashFiles('**/*.txt') }}"
    - run: echo "content" > dir1/file1.txt
    - run: echo "${{ hashFiles('**/*.txt') }}"
    - run: echo "binary" > dir2/file2.bin
    - run: echo "${{ hashFiles('**/*.txt') }}"
    - run: chmod ugo-rwx dir2
    - run: echo "${{ hashFiles('**/*.txt') }}"

  build_and_test:
    name: "Build and Test"

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Test with pytest
      run: |
        mkdir -p test-results
        python -m pytest test --junit-xml test-results/pytest.xml

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Unit Test Results ${{ matrix.python-version }}
        path: "test-results/**/*.xml"

  publish_test_results:
    name: "Publish Unit Tests"
    needs: build_and_test
    runs-on: ubuntu-latest
    if: always()

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        path: artifacts

    - name: Debug Action
      uses: hmarr/debug-action@v1.0.0

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        files: "artifacts/**/*.xml"
        log_level: DEBUG
