name: "CI"
on: [push, pull_request, workflow_dispatch]
permissions: {}

jobs:
  publish_test_results:
    name: "Publish Unit Tests"
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    if: always()

    steps:
    - name: Download test files
      run: |
        wget https://github.com/EnricoMi/publish-unit-test-result-action/files/9044620/caffeine-weakKeysAndWeakValuesStatsSyncGuavaTest-18-results.zip
        unzip caffeine-weakKeysAndWeakValuesStatsSyncGuavaTest-18-results.zip caffeine-weakKeysAndWeakValuesStatsSyncGuavaTest-18.tar.gz
        tar -xzvf caffeine-weakKeysAndWeakValuesStatsSyncGuavaTest-18.tar.gz

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: "caffeine/build/reports/weakKeysAndWeakValuesStatsSyncGuavaTest/results/*.xml"
