name: "CI"
on: [push, pull_request, workflow_dispatch]
permissions: {}

jobs:
  event_file:
    name: "Event File"
    runs-on: ubuntu-latest
    steps:
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Event File
        path: ${{ github.event_path }}

  warn:
    name: "Warning"
    runs-on: ubuntu-latest

    steps:
    - name: warn delimiter
      run: |
        echo "::warning::<<EOL"
        echo "Running this action via 'uses: EnricoMi/publish-unit-test-result-action/composite@v2 is deprecated!"
        echo "Please use an action appropriate for your operating system and shell:"
        echo "- Linux (Bash shell):   EnricoMi/publish-unit-test-result-action/linux@v2"
        echo "- macOS (Bash shell):   EnricoMi/publish-unit-test-result-action/macos@v2"
        echo "- Windows (PowerShell): EnricoMi/publish-unit-test-result-action/windows@v2"
        echo "- Windows (Bash shell): EnricoMi/publish-unit-test-result-action/windows/bash@v2"
        echo "EOL"
      shell: bash
    - name: warn newline
      run: |
        echo -n "::warning::Running this action via 'uses: EnricoMi/publish-unit-test-result-action/composite@v2 is deprecated!%0A"
        echo -n "Please use an action appropriate for your operating system and shell:"
        echo -n "- Linux (Bash shell):   EnricoMi/publish-unit-test-result-action/linux@v2"
        echo -n "- macOS (Bash shell):   EnricoMi/publish-unit-test-result-action/macos@v2"
        echo -n "- Windows (PowerShell): EnricoMi/publish-unit-test-result-action/windows@v2"
        echo -n "- Windows (Bash shell): EnricoMi/publish-unit-test-result-action/windows/bash@v2"
        echo
      shell: bash

  shell:
    name: "Test shell ${{ matrix.machine }}"
    runs-on: ${{ matrix.machine }}
    container:
      image: alpine:latest

    strategy:
      fail-fast: false
      matrix:
        machine: ["ubuntu-latest", "macos-latest", "windows-latest"]

    steps:
    - name: bash
      continue-on-error: true
      run: true
      shell: bash

    - name: sh
      continue-on-error: true
      run: true
      shell: sh

    - name: python
      continue-on-error: true
      run: |
        import sys
        print(sys.platform)
      shell: python

    - name: pwsh
      continue-on-error: true
      run: |
        write-output "pwsh"
      shell: pwsh

    - name: cmd
      continue-on-error: true
      run: |
        echo cmd
      shell: cmd

    - name: powershell
      continue-on-error: true
      run: |
        write-output "pwsh"
      shell: powershell

    - name:
      run: |
        echo "works"

  macos:
    name: "MacOS"

    runs-on: ${{ matrix.machine }}
    strategy:
      fail-fast: false
      matrix:
        machine: ["macos-latest", "macos-14", "macos-15", "macos-26"]

    steps:
    - name: sysctl
      run: sysctl -a
      shell: bash

  build_and_test:
    name: "Build and Test"

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Test with pytest
      run: |
        mkdir -p test-results
        python -m pytest test --junit-xml test-results/pytest.xml

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Unit Test Results ${{ matrix.python-version }}
        path: "test-results/**/*.xml"

  test_success:
    name: "Test success"
    runs-on: ubuntu-latest
    needs: [build_and_test]
    if: always()
    steps:
      - name: "Inspect test outcome"
        run: |
          echo "${{ toJSON( needs ) }}"
          [ "${{ needs.build_and_test.result }}" == "success" ]
        shell: bash

  publish_test_results:
    name: "Publish Unit Tests"
    needs: build_and_test
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    if: always()

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Debug Action
      uses: hmarr/debug-action@v1.0.0

    - name: Publish Unit Test Results (docker)
      uses: EnricoMi/publish-unit-test-result-action/docker@v2
      with:
        check_name: "Test Results (docker)"
        files: "artifacts/**/*.xml"
