name: "CI"
on: [push, pull_request]

jobs:
  event_file:
    name: "Event File"
    runs-on: ubuntu-latest
    steps:
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Event File
        path: ${{ github.event_path }}

  disks:
    name: "Inspect disks"
    runs-on: ubuntu-latest

    steps:
    - name: Largest files
      run: sudo find / -xdev -type f -size +100M -exec du -s {} ';' | sort -rn | head -n 200
    - name: Largest dirs
      run: sudo find / -xdev -type d -exec du -s {} ';' | sort -rn | head -n 1000 | while read size dir; do echo $size $(sudo find "$dir" -type f | wc -l) $dir; done

  cleanup:
    name: "Cleanup disks"
    runs-on: ubuntu-latest

    steps:
    - name: Clean up disk space
      run: |
        echo ::group::Disk space before clean up
        df -h
        echo ::endgroup::

        for dir in /opt/az \
                   /opt/google/chrome \
                   /opt/hostedtoolcache/go \
                   /usr/lib/google-cloud-sdk \
                   /usr/lib/mono \
                   /usr/libexec/gcc \
                   /usr/local/.ghcup \
                   /usr/local/lib/android \
                   /usr/local/share/chromium \
                   /usr/local/share/powershell \
                   /usr/share/dotnet \
                   /usr/share/swift
        do
          echo ::group::Deleting "$dir"
          sudo du -hsc $dir | tail -n1 || true
          sudo rm -rf $dir
          echo ::endgroup::
        done

        echo ::group::Disk space after clean up
        df -h
        echo ::endgroup::

