name: Clean disk

on: [push]

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
    - uses: EnricoMi/max-build-space@improve-logging  #6f167521f22dcb0da67695e16674c4ae5b964e34  # v0.4
      with:
        remove-dotnet: true
        remove-android: true
        remove-haskell: true
        remove-codeql: true
        remove-docker-images: true
        remove-tool-cache: true
