name: Commit

on:
  push:
    branches:
      - "ci-commit-readme-changes"
  workflow_dispatch:

jobs:
  commit:
    name: "Commit"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Change
        run: date >> README.md
        shell: bash

      - name: Commit and push
        env: 
          CI_COMMIT_MESSAGE: Update README.md
          CI_COMMIT_AUTHOR: Github Workflow
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push

