name: Commit

on:
  push:

jobs:
  commit:
    name: "Commit"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Change
        run: echo ${{ github.ref }} >> README.md
        shell: bash

      - name: Commit and push
        if: github.ref != 'refs/heads/master'
        env: 
          CI_COMMIT_MESSAGE: Update README.md
          CI_COMMIT_AUTHOR: Github Workflow
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push

