name: Docker action

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:
  workflow_dispatch:
permissions: {}

jobs:
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: docker-meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/EnricoMi/python
          flavor: |
            latest=false
          tags: |
            type=sha
            type=raw,value=env

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          pull: true
          push: false
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false

  docker-action:
    name: Docker action
    needs: [docker-build]
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Env
        run: env
        shell: bash
      - name: Run action
        uses: EnricoMi/python@env

