name: README & Summary Sync

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Diffing README.rst with docs/summary.rst
      working-directory: ./horovod
      run: |
        sed -e "s/docs\///g" README.rst > docs/README.rst
        patch --quiet -p0 docs/README.rst docs/summary.rst.patch -o docs/summary.rst.as-readme
        diff docs/summary.rst.as-readme docs/summary.rst
