name: "Mac"
on: [push]

jobs:
  build_and_test:
    name: "Build and Test"

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Test with pytest
      run: |
        mkdir -p test-results
        python -m pytest test --continue-on-collection-errors --junit-xml test-results/pytest.xml

    - name: Publish Unit Test Results (composite)
      uses: EnricoMi/publish-unit-test-result-action@branch-composite-action
      if: always()
      with:
        github_token: ${{ github.token }}
        files: "test-results/**/*.xml"
        log_level: DEBUG
