name: Dispatch

on:
  schedule:
  - cron: '18 * * * *'
  workflow_dispatch:
    inputs:
      branch:
        description: 'list of branches to publish (JSON)'
        required: true
        default: '["master", "branch-3.5", "branch-3.4", "branch-3.3"]'

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch: ${{ fromJSON( inputs.branch ) }}

    steps:
    - run: echo ${{ matrix.branch }} ${{ inputs.branch }}
      shell: bash

