name: "CI Workflow Run"
on:
  workflow_run:
    workflows: ["CI"]
    types: 
      - completed
permissions: {}

jobs:
  publish_test_results:
    name: "Publish Unit Tests"
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'

    steps:
    - name: Download and Extract Artifacts
      uses: dawidd6/action-download-artifact@246dbf436b23d7c49e21a7ab8204ca9ecd1fe615
      with:
        run_id: ${{ github.event.workflow_run.id }}
        path: artifacts

    - name: Debug Action
      uses: hmarr/debug-action@v1.0.0

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        check_name: Unit Test Results (Workflow Run)
        commit: ${{ github.event.workflow_run.head_sha }}
        event_file: artifacts/Event File/event.json
        event_name: ${{ github.event.workflow_run.event }}
        files: "artifacts/**/*.xml"
        log_level: DEBUG
